// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodPlaylistGenerator.Data;

#nullable disable

namespace MoodPlaylistGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FFD700",
                            Description = "Upbeat and joyful tunes.",
                            Name = "Happy"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#1E90FF",
                            Description = "Melancholic and emotional songs.",
                            Name = "Sad"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FF4500",
                            Description = "Fast-paced and high-energy tracks.",
                            Name = "Energetic"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#3CB371",
                            Description = "Relaxing and peaceful music.",
                            Name = "Calm"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#FF69B4",
                            Description = "Love songs and ballads.",
                            Name = "Romantic"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#6A5ACD",
                            Description = "Instrumental or ambient music for concentration.",
                            Name = "Focus"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#DC143C",
                            Description = "Motivational tracks for exercise.",
                            Name = "Workout"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#F08080",
                            Description = "Music to get you dancing.",
                            Name = "Party"
                        });
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MoodId");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.PlaylistSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistSongs");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YouTubeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.SongMood", b =>
                {
                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId", "MoodId");

                    b.HasIndex("MoodId");

                    b.ToTable("SongMoods");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Playlist", b =>
                {
                    b.HasOne("MoodPlaylistGenerator.Models.Mood", "Mood")
                        .WithMany("Playlists")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodPlaylistGenerator.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.PlaylistSong", b =>
                {
                    b.HasOne("MoodPlaylistGenerator.Models.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodPlaylistGenerator.Models.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Song", b =>
                {
                    b.HasOne("MoodPlaylistGenerator.Models.User", "User")
                        .WithMany("Songs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.SongMood", b =>
                {
                    b.HasOne("MoodPlaylistGenerator.Models.Mood", "Mood")
                        .WithMany("SongMoods")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodPlaylistGenerator.Models.Song", "Song")
                        .WithMany("SongMoods")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Mood", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("SongMoods");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.Song", b =>
                {
                    b.Navigation("PlaylistSongs");

                    b.Navigation("SongMoods");
                });

            modelBuilder.Entity("MoodPlaylistGenerator.Models.User", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
